In [1]:
import torch

In [2]:
import torchvision

In [3]:
import torch.nn as nn

In [4]:
import numpy as np

In [5]:
import torchvision.transforms as transforms

In [6]:
x = torch.tensor(1.,requires_grad=True)
w = torch.tensor(2.,requires_grad=True)
b = torch.tensor(3.,requires_grad=True)

y = w * x + b

In [7]:
y

tensor(5., grad_fn=<AddBackward0>)

In [8]:
y.backward()

In [9]:
print(x.grad)

tensor(2.)


In [10]:
print(w.grad)

tensor(1.)


In [11]:
print(b.grad)

tensor(1.)


In [12]:
x = torch.randn(10,3)

In [13]:
y = torch.rand(10,2)

In [14]:
criterion = nn.MSELoss()

In [15]:
linear = nn.Linear(3,2)

In [16]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.3024, -0.0282, -0.1863],
        [ 0.1780, -0.3881, -0.0288]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2463, -0.2409], requires_grad=True)


In [19]:
optimizer = torch.optim.SGD(linear.parameters(),lr=0.01)

In [20]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [21]:
pred = linear(x)

In [22]:
loss = criterion(pred,y)

In [23]:
print(loss)

tensor(0.8861, grad_fn=<MseLossBackward0>)


In [24]:
loss.backward()

In [25]:
print('dL/dw: ',linear.weight.grad)
print('dL/db',linear.bias.grad)

dL/dw:  tensor([[ 0.0772, -0.1581, -0.2454],
        [ 0.4160, -0.5090,  0.3495]])
dL/db tensor([-0.6643, -1.0080])


In [26]:
optimizer.step()

In [27]:
pred = linear(x)

In [28]:
loss = criterion(pred,y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  0.865197479724884


In [33]:
x = np.array([[1,2],[3,4]])
y = torch.from_numpy(x)

In [34]:
z = y.numpy()

In [35]:
z

array([[1, 2],
       [3, 4]])

In [36]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

100.0%


Extracting ../../data/cifar-10-python.tar.gz to ../../data/


In [37]:
image,label = train_dataset[0]

In [38]:
print(image.size())

torch.Size([3, 32, 32])


In [39]:
print(label)

6


In [40]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,batch_size=64,shuffle=True)

In [41]:
data_iter = iter(train_loader)

In [44]:
# images, labels = data_iter.next()


In [45]:
for images, labels in train_loader:
    # Training code should be written here.
    pass

In [47]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        pass
    def __getitem__(self,index):
        pass
    def __len__(self):
        return 0

In [48]:
custom_dataset = CustomDataset()

In [51]:
#    train_load = torch.utils.data.DataLoader(dataset=custom_dataset,batch_size=64,shuffle=True)

In [52]:
resnet = torchvision.models.resnet18(pretrained=True)

/home/saif/miniconda3/envs/torch_cpu/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/saif/miniconda3/envs/torch_cpu/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /home/saif/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100.0%


In [53]:
for param in resnet.parameters():
    param.requires_grad = False

In [54]:
resnet.fc = nn.Linear(resnet.fc.in_features,100)

In [55]:
images = torch.randn(64,3,224,224)

In [56]:
outputs = resnet(images)

In [57]:
print(outputs)

tensor([[ 0.0658, -0.4187,  0.3861,  ..., -1.0678,  0.9972,  0.7568],
        [ 0.0379,  0.1688,  0.1172,  ..., -1.0311,  1.2779,  0.7174],
        [ 0.1292,  0.4993,  0.2917,  ..., -1.3379,  0.0869,  1.2825],
        ...,
        [ 0.2281,  0.1936,  0.3233,  ..., -1.2195,  1.6533,  0.5336],
        [ 0.5507,  0.2985,  0.3771,  ..., -0.4240,  0.9184,  0.8091],
        [-0.0924, -0.2147,  0.4763,  ..., -1.6822,  1.0555,  0.9722]],
       grad_fn=<AddmmBackward0>)


In [58]:
torch.save(resnet,'model.ckpt')

In [59]:
model = torch.load('model.ckpt')

/tmp/ipykernel_137931/240101920.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('model.ckpt')


In [60]:
torch.save(resnet.state_dict(),'params.ckpt')

In [61]:
resnet.load_state_dict(torch.load('params.ckpt'))

/tmp/ipykernel_137931/1937668769.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  resnet.load_state_dict(torch.load('params.ckpt'))


<All keys matched successfully>